// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqjymhgHwYUyGPJC5U9DevgJjoaiIaqN4',
    appId: '1:1045049966514:web:92751eba9de455c35f6eab',
    messagingSenderId: '1045049966514',
    projectId: 'fir-web-app-78930',
    authDomain: 'fir-web-app-78930.firebaseapp.com',
    storageBucket: 'fir-web-app-78930.appspot.com',
    measurementId: 'G-SWJZWPX45H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-lt5yumHSvZgj46P7bgBZvV0nUb4v9og',
    appId: '1:1045049966514:android:4773f2c9f07e23695f6eab',
    messagingSenderId: '1045049966514',
    projectId: 'fir-web-app-78930',
    storageBucket: 'fir-web-app-78930.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxElBl3cQvrabn9WaNVWya1gLWYgHh6nU',
    appId: '1:1045049966514:ios:02551139f6e205db5f6eab',
    messagingSenderId: '1045049966514',
    projectId: 'fir-web-app-78930',
    storageBucket: 'fir-web-app-78930.appspot.com',
    iosBundleId: 'com.example.firebaseAppWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxElBl3cQvrabn9WaNVWya1gLWYgHh6nU',
    appId: '1:1045049966514:ios:02551139f6e205db5f6eab',
    messagingSenderId: '1045049966514',
    projectId: 'fir-web-app-78930',
    storageBucket: 'fir-web-app-78930.appspot.com',
    iosBundleId: 'com.example.firebaseAppWeb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqjymhgHwYUyGPJC5U9DevgJjoaiIaqN4',
    appId: '1:1045049966514:web:9248a566f68374975f6eab',
    messagingSenderId: '1045049966514',
    projectId: 'fir-web-app-78930',
    authDomain: 'fir-web-app-78930.firebaseapp.com',
    storageBucket: 'fir-web-app-78930.appspot.com',
    measurementId: 'G-K5S55D8J2P',
  );
}
